# Generated by Django 2.1.7 on 2019-03-24 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('doctors', models.ManyToManyField(to='health.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('familyMember', models.ManyToManyField(related_name='_person_familyMember_+', to='health.Person')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msp', models.IntegerField(unique=True)),
                ('sin', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=200)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='health.Person')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='health.Person'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Person'),
        ),
    ]
