# Generated by Django 2.1.7 on 2019-03-24 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msp', models.IntegerField(unique=True)),
                ('sin', models.IntegerField(unique=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='health.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='person',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
