# Generated by Django 2.1.7 on 2019-03-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20190323_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
