# Generated by Django 2.1.7 on 2019-03-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='familyMember',
            field=models.ManyToManyField(null=True, related_name='_person_familyMember_+', to='health.Person'),
        ),
    ]
